version: "3"

services:

  nginx:
    build: './docker/nginx'
    container_name: docker-compose-nginx
    ports:
      - '8080:80'
    volumes:
      - ./public:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: './docker/php'
    container_name: docker-compose-php
    ports:
      - '9000:9000'
    volumes:
      - ./public:/app
    depends_on:
      - mysql

  mysql:
    build: './docker/mysql'
    platform: x86_64
    ports:
      - '3306:3306'
    volumes:
      - /opt/homebrew/var/mysql:/var/lib/mysql
